# Generated by Django 3.0.5 on 2020-04-26 07:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('profile_image', models.ImageField(upload_to='image/%Y/%m/%d')),
                ('preferences', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=255)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('extra', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API_demo.Meta')),
                ('name', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=2000)),
                ('nm_meta', models.CharField(blank=True, max_length=2000)),
                ('extra', models.CharField(blank=True, max_length=2000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('API_demo.meta',),
        ),
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API_demo.Meta')),
                ('type', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('nm_meta', models.CharField(blank=True, max_length=2000)),
                ('extra', models.CharField(blank=True, max_length=2000)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_demo.Projects')),
            ],
            bases=('API_demo.meta',),
        ),
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API_demo.Meta')),
                ('data', models.FileField(upload_to='files/')),
                ('nm_meta', models.CharField(max_length=2000)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_demo.Floors')),
            ],
            bases=('API_demo.meta',),
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('meta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='API_demo.Meta')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=255)),
                ('app_redirect', models.CharField(max_length=2000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('API_demo.meta',),
        ),
    ]
