# Generated by Django 3.0.5 on 2020-04-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blobs', to='API_demo.Floors'),
        ),
    ]
